	.arch armv7-a
	.eabi_attribute 27, 3
	.fpu neon
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 6
	.eabi_attribute 34, 1
	.eabi_attribute 18, 4
	.file	"aecm_core_neon_offsets.c"
	.text
.Ltext0:
	.cfi_sections	.debug_frame
	.global	offset_aecm_dfaCleanQDomain
	.data
	.align	2
	.type	offset_aecm_dfaCleanQDomain, %object
	.size	offset_aecm_dfaCleanQDomain, 4
offset_aecm_dfaCleanQDomain:
	.word	13976
	.global	offset_aecm_outBuf
	.align	2
	.type	offset_aecm_outBuf, %object
	.size	offset_aecm_outBuf, 4
offset_aecm_outBuf:
	.word	15988
	.global	offset_aecm_xBuf
	.align	2
	.type	offset_aecm_xBuf, %object
	.size	offset_aecm_xBuf, 4
offset_aecm_xBuf:
	.word	15976
	.global	offset_aecm_dBufNoisy
	.align	2
	.type	offset_aecm_dBufNoisy, %object
	.size	offset_aecm_dBufNoisy, 4
offset_aecm_dBufNoisy:
	.word	15984
	.global	offset_aecm_dBufClean
	.align	2
	.type	offset_aecm_dBufClean, %object
	.size	offset_aecm_dBufClean, 4
offset_aecm_dBufClean:
	.word	15980
	.global	offset_aecm_channelStored
	.align	2
	.type	offset_aecm_channelStored, %object
	.size	offset_aecm_channelStored, 4
offset_aecm_channelStored:
	.word	15964
	.global	offset_aecm_channelAdapt16
	.align	2
	.type	offset_aecm_channelAdapt16, %object
	.size	offset_aecm_channelAdapt16, 4
offset_aecm_channelAdapt16:
	.word	15968
	.global	offset_aecm_channelAdapt32
	.align	2
	.type	offset_aecm_channelAdapt32, %object
	.size	offset_aecm_channelAdapt32, 4
offset_aecm_channelAdapt32:
	.word	15972
	.global	offset_aecm_real_fft
	.align	2
	.type	offset_aecm_real_fft, %object
	.size	offset_aecm_real_fft, 4
offset_aecm_real_fft:
	.word	17216
	.text
.Letext0:
	.file 1 "sources/modules/audio_processing/aecm/aecm_core_neon_offsets.c"
	.section	.debug_info,"",%progbits
.Ldebug_info0:
	.4byte	0x107
	.2byte	0x4
	.4byte	.Ldebug_abbrev0
	.byte	0x4
	.uleb128 0x1
	.4byte	.LASF20
	.byte	0x1
	.4byte	.LASF21
	.4byte	.LASF22
	.4byte	.Ldebug_line0
	.uleb128 0x2
	.byte	0x4
	.byte	0x5
	.ascii	"int\000"
	.uleb128 0x3
	.byte	0x4
	.byte	0x7
	.4byte	.LASF0
	.uleb128 0x3
	.byte	0x1
	.byte	0x6
	.4byte	.LASF1
	.uleb128 0x3
	.byte	0x1
	.byte	0x8
	.4byte	.LASF2
	.uleb128 0x3
	.byte	0x2
	.byte	0x5
	.4byte	.LASF3
	.uleb128 0x3
	.byte	0x2
	.byte	0x7
	.4byte	.LASF4
	.uleb128 0x3
	.byte	0x8
	.byte	0x5
	.4byte	.LASF5
	.uleb128 0x3
	.byte	0x8
	.byte	0x7
	.4byte	.LASF6
	.uleb128 0x3
	.byte	0x4
	.byte	0x7
	.4byte	.LASF7
	.uleb128 0x3
	.byte	0x4
	.byte	0x5
	.4byte	.LASF8
	.uleb128 0x3
	.byte	0x4
	.byte	0x7
	.4byte	.LASF9
	.uleb128 0x3
	.byte	0x1
	.byte	0x8
	.4byte	.LASF10
	.uleb128 0x4
	.4byte	.LASF11
	.byte	0x1
	.byte	0x12
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_dfaCleanQDomain
	.uleb128 0x4
	.4byte	.LASF12
	.byte	0x1
	.byte	0x13
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_outBuf
	.uleb128 0x4
	.4byte	.LASF13
	.byte	0x1
	.byte	0x14
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_xBuf
	.uleb128 0x4
	.4byte	.LASF14
	.byte	0x1
	.byte	0x15
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_dBufNoisy
	.uleb128 0x4
	.4byte	.LASF15
	.byte	0x1
	.byte	0x16
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_dBufClean
	.uleb128 0x4
	.4byte	.LASF16
	.byte	0x1
	.byte	0x17
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_channelStored
	.uleb128 0x4
	.4byte	.LASF17
	.byte	0x1
	.byte	0x18
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_channelAdapt16
	.uleb128 0x4
	.4byte	.LASF18
	.byte	0x1
	.byte	0x19
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_channelAdapt32
	.uleb128 0x4
	.4byte	.LASF19
	.byte	0x1
	.byte	0x1a
	.4byte	0x1d
	.uleb128 0x5
	.byte	0x3
	.4byte	offset_aecm_real_fft
	.byte	0
	.section	.debug_abbrev,"",%progbits
.Ldebug_abbrev0:
	.uleb128 0x1
	.uleb128 0x11
	.byte	0x1
	.uleb128 0x25
	.uleb128 0xe
	.uleb128 0x13
	.uleb128 0xb
	.uleb128 0x3
	.uleb128 0xe
	.uleb128 0x1b
	.uleb128 0xe
	.uleb128 0x10
	.uleb128 0x17
	.byte	0
	.byte	0
	.uleb128 0x2
	.uleb128 0x24
	.byte	0
	.uleb128 0xb
	.uleb128 0xb
	.uleb128 0x3e
	.uleb128 0xb
	.uleb128 0x3
	.uleb128 0x8
	.byte	0
	.byte	0
	.uleb128 0x3
	.uleb128 0x24
	.byte	0
	.uleb128 0xb
	.uleb128 0xb
	.uleb128 0x3e
	.uleb128 0xb
	.uleb128 0x3
	.uleb128 0xe
	.byte	0
	.byte	0
	.uleb128 0x4
	.uleb128 0x34
	.byte	0
	.uleb128 0x3
	.uleb128 0xe
	.uleb128 0x3a
	.uleb128 0xb
	.uleb128 0x3b
	.uleb128 0xb
	.uleb128 0x49
	.uleb128 0x13
	.uleb128 0x3f
	.uleb128 0x19
	.uleb128 0x2
	.uleb128 0x18
	.byte	0
	.byte	0
	.byte	0
	.section	.debug_aranges,"",%progbits
	.4byte	0x14
	.2byte	0x2
	.4byte	.Ldebug_info0
	.byte	0x4
	.byte	0
	.2byte	0
	.2byte	0
	.4byte	0
	.4byte	0
	.section	.debug_line,"",%progbits
.Ldebug_line0:
	.section	.debug_str,"MS",%progbits,1
.LASF5:
	.ascii	"long long int\000"
.LASF0:
	.ascii	"unsigned int\000"
.LASF19:
	.ascii	"offset_aecm_real_fft\000"
.LASF11:
	.ascii	"offset_aecm_dfaCleanQDomain\000"
.LASF14:
	.ascii	"offset_aecm_dBufNoisy\000"
.LASF17:
	.ascii	"offset_aecm_channelAdapt16\000"
.LASF7:
	.ascii	"long unsigned int\000"
.LASF20:
	.ascii	"GNU C 4.8 -mbionic -march=armv7-a -mfpu=vfpv3-d16 -"
	.ascii	"mfloat-abi=softfp -mthumb -marm -march=armv7-a -mfp"
	.ascii	"u=neon -mfloat-abi=softfp -mtls-dialect=gnu -g -Os "
	.ascii	"-O0 -fpic -ffunction-sections -funwind-tables -fsta"
	.ascii	"ck-protector -fno-strict-aliasing -finline-limit=64"
	.ascii	" -fno-omit-frame-pointer -flax-vector-conversions\000"
.LASF18:
	.ascii	"offset_aecm_channelAdapt32\000"
.LASF12:
	.ascii	"offset_aecm_outBuf\000"
.LASF21:
	.ascii	"sources/modules/audio_processing/aecm/aecm_core_neo"
	.ascii	"n_offsets.c\000"
.LASF6:
	.ascii	"long long unsigned int\000"
.LASF2:
	.ascii	"unsigned char\000"
.LASF16:
	.ascii	"offset_aecm_channelStored\000"
.LASF10:
	.ascii	"char\000"
.LASF8:
	.ascii	"long int\000"
.LASF13:
	.ascii	"offset_aecm_xBuf\000"
.LASF4:
	.ascii	"short unsigned int\000"
.LASF1:
	.ascii	"signed char\000"
.LASF22:
	.ascii	"/storage/Development/CSipSimple-mirror/CSipSimple/j"
	.ascii	"ni/webrtc\000"
.LASF15:
	.ascii	"offset_aecm_dBufClean\000"
.LASF3:
	.ascii	"short int\000"
.LASF9:
	.ascii	"sizetype\000"
	.ident	"GCC: (GNU) 4.8"
	.section	.note.GNU-stack,"",%progbits
